@host=http://localhost:5110

GET {{host}}/dinners
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxN2MzN2UyMC0xMTk5LTRhNWYtYTFjMC1hZDg2MDU2YzQwYTUiLCJnaXZlbl9uYW1lIjoidGVzdDIiLCJmYW1pbHlfbmFtZSI6InRlc3QyIiwianRpIjoiOWUxYTUzMGYtYjMzYS00YzBkLTljNmYtOTE2M2I1OWRmYjg0IiwiZXhwIjoxNjcwODY4NDA1LCJpc3MiOiJCdWJlckRpbm5lciIsImF1ZCI6IkJ1YmVyRGlubmVyIn0.f5hQsyT3_tPgEh3q8iGRYnCrZyVfFxmPUz20T_J9rEU